#!/bin/bash

set -o errexit
# set -o pipefail
set -o nounset


python manage.py migrate

while true; do
  echo "Re-starting Django runserver"
  # python manage.py runserver 0.0.0.0:8000
  python manage.py runserver_plus 0.0.0.0:8000
done
